Refining split
insightsengineering/rtables.officer pull request #19
Opened 2024-11-20 15:44 UTC by Melkiades

Fixes #18

2024-11-20 15:47 UTC, Melkiades commented
I have read the CLA Document and I hereby sign the CLA

2024-11-21 06:20 UTC, shajoezhu commented on R/export_as_docx.R
> +#'   we suggest that you use [tt_to_flextable()] prior to `export_as_docx`. Only the `titles_as_header` and
good catch

2024-11-21 14:53 UTC, shajoezhu commented on R/package.R
> -#' @import rtables
these are needed

2024-11-21 14:55 UTC, shajoezhu requested changes
hi @Melkiades , can you add formatters for rtables :: to 

all_footers all_titles collect_leaves coltree decimal_align font_spec
  make_row_df matrix_form mf_aligns mf_nlheader mf_spans mf_strings
  obj_name paginate_table propose_column_widths spans_to_viscell
  value_names

thanks!

2024-11-22 14:37 UTC, shajoezhu approved these changes
lgtm! thanks @Melkiades

2024-11-22 14:44 UTC, merged